namespace NexoLogic.Models.Enums;

/// <summary>
/// Lexical classifications for raw source string evaluation.
/// Defines the complete grammatical dictionary mapped by the Nexo Parser (NPL).
/// </summary>
public enum TokenType
{
    // --- Modular Inclusion ---
    Using,

    // --- Executable Scopes ---
    Do,

    // --- Scalar Literals ---
    Number,         // e.g., 10, 42
    String,         // e.g., "Hello World"
    Identifier,     // Unreserved names: x, counter, index
    True,           // Boolean true literal
    False,          // Boolean false literal
    
    // --- Arithmetic Binary Nodes ---
    Plus,           // +
    Minus,          // -
    Multiply,       // *
    Divide,         // /
    Assign,         // = (Memory Assignment)

    // --- Relational & Logical Operators ---
    EqualEqual,     // == (Equality Check)
    NotEqual,       // !=
    GreaterThan,    // >
    LessThan,       // <
    GreaterEqual,   // >=
    LessEqual,      // <=
    And,            // Logical Conjunction (&&)
    Or,             // Logical Disjunction (||)
    Not,            // Logical Negation (!)

    // --- Control Flow Keywords ---
    If,             // Conditional Branching
    Else,           // Conditional Fallback
    While,          // Pre-tested Iteration Cycle
    Write,          // Standard Output Stream
    Read,           // Standard Input Stream
    Return,         // Scope Exit / Yield
    Break,          // Iteration Interruption
    Continue,       // Iteration Advancement
    
    // --- Structural Syntax Groupings ---
    OpenParen,      // ( Priority escalation
    CloseParen,     // ) 
    OpenBrace,      // { Block Initiation
    CloseBrace,     // } Block Termination
    OpenBracket,    // [ Index Initiation
    CloseBracket,   // ] Index Termination
    Colon,          // : Scope initiation boundary (Python-esque)
    Comma,          // , Parameter delimiting
    Dot,            // . Reference Traversal
    
    // --- Lexical State Flags ---
    Comment,        // Line Ignore Symbol ('<3')
    EOF             // End of File marker forcing parser termination
}

/// <summary>
/// Synthesized atomic payload generated by the Lexical Analyzer.
/// Carries structural metadata alongside the literal string segment evaluated.
/// </summary>
public record Token(TokenType Type, string Value);