using NexoLogic.Models;
using NexoLogic.Models.Enums;
using System;
using System.Collections.Generic;

namespace NexoLogic.Parsing;

/// <summary>
/// LL(1) Recursive Descent Parser for formulating Abstract Syntax Trees (AST).
/// Consumes the linear token stream generated by the Lexical Analyzer and
/// synthesizes hierarchical execution blocks for MSIL emission.
/// </summary>
public class Parser {
    private readonly List<Token> _tokens;
    private int _pos = 0;

    public Parser(List<Token> tokens) => _tokens = tokens;
    
    /// <summary>
    /// Retrieves the current token under the parser's evaluation head.
    /// Safely clamps to the EOF token if the stream bounds are exceeded.
    /// </summary>
    private Token Current => _pos < _tokens.Count ? _tokens[_pos] : _tokens[^1];
    
    /// <summary>
    /// Peeks forward in the token stream by the specified distance.
    /// Crucial for resolving LL(1) ambiguity in generic statements like Assignments vs Expressions.
    /// </summary>
    private Token Peek(int dist) => _pos + dist < _tokens.Count ? _tokens[_pos + dist] : _tokens[^1];
    
    /// <summary>
    /// Consumes the current token and forcefully advances the read head by one discrete step.
    /// </summary>
    private Token Next() => _tokens[_pos++];

    /// <summary>
    /// Bootstraps the syntax analysis algorithm, sequentially consuming tokens 
    /// until the absolute End-Of-File boundary is successfully reached.
    /// </summary>
    public List<AstNodes.Statement> Parse() {
        var stmts = new List<AstNodes.Statement>();
        while (Current.Type != TokenType.EOF) {
            stmts.Add(ParseStatement());
        }
        return stmts;
    }

    /// <summary>
    /// Statement Resolution Router.
    /// Checks the structural root of the current segment and jumps to the relevant AST payload constructor.
    /// </summary>
    private AstNodes.Statement ParseStatement() {
        // Control Flow: Conditional Branching
        if (Current.Type == TokenType.If) {
            Next(); 
            var cond = ParseExpression(); 
            if (Current.Type == TokenType.Colon) Next(); // Optional Python/Nim style colon
            
            var then = ParseBody(); 
            AstNodes.Statement? @else = null;
            
            if (Current.Type == TokenType.Else) { 
                Next(); 
                if (Current.Type == TokenType.Colon) Next(); 
                @else = ParseBody(); 
            }
            return new AstNodes.IfStatement(cond, then, @else);
        }
        
        // Control Flow: Iterative Cycles
        if (Current.Type == TokenType.While) {
            Next(); 
            var cond = ParseExpression(); 
            if (Current.Type == TokenType.Colon) Next();
            
            return new AstNodes.WhileStatement(cond, ParseBody());
        }
        
        // System I/O Emission
        if (Current.Type == TokenType.Write) { 
            Next(); 
            return new AstNodes.PrintStatement(ParseExpression()); 
        }
        
        // Memory Allocation & Assignment Evaluation
        // Employs a lookahead to differentiate between a solitary expression and an explicit assignment
        if (Current.Type == TokenType.Identifier && Peek(1).Type == TokenType.Assign) {
            var name = Next().Value; 
            Next(); // Consume Assignment '='
            return new AstNodes.AssignmentStatement(name, ParseExpression());
        }
        
        // Modular Injection / Package Importing
        if (Current.Type == TokenType.Using) {
            Next(); 
            if (Current.Type != TokenType.Identifier)
                throw new Exception("[NXC-001] Syntax Analysis Error: Expected a valid namespace or module identifier directly after the 'using' directive.");
            
            string moduleName = Next().Value;
            while (Current.Type == TokenType.Dot) {
                Next(); // Consume namespace structural delimitter '.'
                if (Current.Type != TokenType.Identifier)
                    throw new Exception("[NXC-002] Syntax Analysis Error: Expected trailing identifier module extension immediately following the '.' separator.");
                moduleName += "." + Next().Value;
            }
            return new AstNodes.UsingStatement(moduleName);
        }
        
        // Function/Method Formal Declaration
        if (Current.Type == TokenType.Do) {
            Next(); 
            string name = Next().Value;
            
            Next(); // Consume '('
            var parameters = new List<string>();
            while (Current.Type != TokenType.CloseParen) {
                parameters.Add(Next().Value);
                if (Current.Type == TokenType.Comma) Next();
            }
            Next(); // Consume ')'
            
            var body = ParseBody(); 
            return new AstNodes.FunctionStatement(name, parameters, (AstNodes.BlockStatement)body);
        }
        
        // Execution Exit Point & Stack Returning
        if (Current.Type == TokenType.Return) {
            Next();
            AstNodes.Expression? expr = null;
            
            // Ambiguity Resolution: Ascertain if the return value exists by checking trailing delimiters
            if (Current.Type != TokenType.CloseBrace && Current.Type != TokenType.EOF) {
                expr = ParseExpression();
            }
            return new AstNodes.ReturnStatement(expr);
        }
        
        // Loop Interruptors
        if (Current.Type == TokenType.Break) {
            Next(); return new AstNodes.BreakStatement();
        }
        if (Current.Type == TokenType.Continue) {
            Next(); return new AstNodes.ContinueStatement();
        }
        
        // Fallback: Default to a transient Expression wrapper if no explicit control structure matches
        var expStmt = ParseExpression();
        return new AstNodes.ExpressionStatement(expStmt);
    }

    /// <summary>
    /// Context Body Resolution.
    /// Iterates recursively over internal statements trapped within scoping braces.
    /// Re-routes purely to a singular statement evaluation if brackets are omitted.
    /// </summary>
    private AstNodes.Statement ParseBody() {
        if (Current.Type == TokenType.OpenBrace) {
            Next(); 
            var stmts = new List<AstNodes.Statement>();
            while (Current.Type != TokenType.CloseBrace && Current.Type != TokenType.EOF) {
                stmts.Add(ParseStatement());
            }
            Next(); 
            return new AstNodes.BlockStatement(stmts);
        }
        return ParseStatement();
    }

    // -------------------------------------------------------------
    // Order of Operations: Binary Descent Algorithms
    // Progressively traverses priority depth from logical checks downwards to atomic values
    // -------------------------------------------------------------
    
    private AstNodes.Expression ParseExpression() => ParseEquality();
    
    private AstNodes.Expression ParseEquality() {
        var left = ParseComparison();
        while (Current.Type is TokenType.EqualEqual or TokenType.NotEqual)
            left = new AstNodes.BinaryExpression(left, Next().Value, ParseComparison());
        return left;
    }
    
    private AstNodes.Expression ParseComparison() {
        var left = ParseTerm();
        while (Current.Type is TokenType.GreaterThan or TokenType.GreaterEqual or TokenType.LessThan or TokenType.LessEqual)
            left = new AstNodes.BinaryExpression(left, Next().Value, ParseTerm());
        return left;
    }
    
    private AstNodes.Expression ParseTerm() {
        var left = ParseFactor();
        while (Current.Type is TokenType.Plus or TokenType.Minus)
            left = new AstNodes.BinaryExpression(left, Next().Value, ParseFactor());
        return left;
    }
    
    private AstNodes.Expression ParseFactor() {
        var left = ParsePrimary();
        while (Current.Type is TokenType.Multiply or TokenType.Divide)
            left = new AstNodes.BinaryExpression(left, Next().Value, ParsePrimary());
        return left;
    }
    
    /// <summary>
    /// Atomic Evaluator.
    /// Flattens the deepest nodes (primitives, raw variables, direct invocations) into final leaf trees.
    /// </summary>
    private AstNodes.Expression ParsePrimary() {
        if (Current.Type == TokenType.Read) { Next(); return new AstNodes.ReadExpression(); }
        if (Current.Type == TokenType.Number) { return new AstNodes.NumberExpression(int.Parse(Next().Value)); }
        if (Current.Type == TokenType.String) { return new AstNodes.StringExpression(Next().Value); }
        if (Current.Type == TokenType.True) { Next(); return new AstNodes.BoolExpression(true); }
        if (Current.Type == TokenType.False) { Next(); return new AstNodes.BoolExpression(false); }
        
        if (Current.Type == TokenType.Identifier) {
            string name = Next().Value;
            
            // Differentiates raw scalar variable references from executable function invocations
            if (Current.Type == TokenType.OpenParen) { 
                Next();
                var args = new List<AstNodes.Expression>();
                while (Current.Type != TokenType.CloseParen && Current.Type != TokenType.EOF) {
                    args.Add(ParseExpression());
                    if (Current.Type == TokenType.Comma) Next();
                }
                if (Current.Type == TokenType.CloseParen) Next();
                return new AstNodes.CallExpression(name, args);
            }
            return new AstNodes.VariableExpression(name);
        }
        
        // Priority Override via Parentheses Escaping
        if (Current.Type == TokenType.OpenParen) { 
            Next(); 
            var e = ParseExpression(); 
            Next(); 
            return e; 
        }
        
        throw new Exception($"[NXC-003] AST Resolution Error: Unexpected token '{Current.Value}' (Type: {Current.Type}) encountered during atomic primary expression evaluation.");
    }
}